name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.0
      - name: Install OpenCV
        uses: ./ # Uses an action in the root directory
        with:
          opencv-version: '4.10.0'
      - name: Build Project
        uses: threeal/cmake-action@v2.0.0